### ISSUE TITLE
where to download the dataset

### ISSUE THREAD

**Issue by Justinhzy** [geekfeiw/CSI-Net#2]

**Comment by geekfeiw** [comment]
in the folder of 'data'

**Comment by pribadihcr** [comment]
Hi @geekfeiw,

In the data folder is it just contain person recognition?. 
Can you upload the fall detection dataset as well. Thanks

**Comment by geekfeiw** [comment]
Hi @pribadihcr
Glad for your interest in this project.
I have uploaded the fall detection dataset to the dataset folder.
The label is the N_samplex2 matrix, where the first column is for fall or not-fall,  and the second column is for the position where data collected.
